name: Training refactoring

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Run Yarn
        run: yarn
      - name: Installing dépendencies chapter 1
        run: cd "chapter 1/" && yarn install
      - name: Run tests chapter 1
        run: cd "chapter 1/" && yarn test
      - name: Run Coverage chapter 1
        run: cd "chapter 1/" && yarn coverage
